# flake8: noqa
ASS_HEADER = """[Script Info]
; Script generated by Aegisub r8942
; http://www.aegisub.org/
Title:
ScriptType: v4.00+
PlayDepth: 0
ScaledBorderAndShadow: yes
PlayResX: 1920
PlayResY: 1080
YCbCr Matrix: TV.601

[Aegisub Project Garbage]
Audio File: {}
Video File: {}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,思源黑体 CN Heavy,81,&H00FFFFFF,&H000019FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,4,3,2,11,11,11,1
Style: 备注,思源黑体 CN Heavy,75,&H00FFFFFF,&H000019FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,4,3,8,11,11,11,1
Style: 水印,胡晓波男神体,30,&H32FFFFFF,&H000000FF,&HFF000000,&HFF000000,0,0,0,0,100,100,0,0,1,3,0,7,15,15,15,1

[Events]
Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,2:00:00.00,水印,,0,0,0,,道德天尊战神菌"""
